### ISSUE TITLE
Opening game gives error C2-12828-1 on boot

### ISSUE THREAD

**Issue by L1ghtingBolt** [SonicMastr/godot#12]
**Godot version:**
3.rc5 
**OS/device including version:**
Windows 11
**Issue description:**
After compiling, both with or without "Export with debug" gives that error.
Also random build are impossible to install because the param.sfo is corrupted and gives error about INVALID_TITLEID: 0xF0030000, fixes recompiling.
**Steps to reproduce:**
Happens in my project, but works fine for every other platform, so I guess it's the PS Vita exporter
**Minimal reproduction project:**
I don't know the cause so I will send the project I have the error with:
https://www.mediafire.com/file/hvk0w0tmamjcb30/project.zip/file

**Comment by SonicMastr** [comment]
I don't need the project for this. I need to m the vpk

**Comment by L1ghtingBolt** [comment]
Happens every time I try to build the project even when I think param.sfo is not corrupted but I'll send it tho
https://www.mediafire.com/file/uk9b8ssmzeckjgr/SpacePlanters.vpk/file VPK
https://www.mediafire.com/file/p38wpi9yqkkroyx/param.sfo/file param.sfo
Did it work when you built the project?

**Comment by L1ghtingBolt** [comment]
I don't think it's a param.sfo problem at all, I tried exporting the godot pkg and putting it on a older version that was working and gave the same error, so I think the problem is in the project, maybe some feature being used that is not supported in the PS Vita

**Comment by SonicMastr** [comment]
I checked the logs, the application runs out of memory on initialization. I'll see if modifying memory split helps

**Comment by L1ghtingBolt** [comment]
> I checked the logs, the application runs out of memory on initialization. I'll see if modifying memory split helps

Thanks! How to check the logs, tho?

**Comment by SonicMastr** [comment]
> > I checked the logs, the application runs out of memory on initialization. I'll see if modifying memory split helps
> 
> Thanks! How to check the logs, tho?

I would recommend using PrincessLog here: https://github.com/CelesteBlue-dev/PSVita-RE-tools/tree/master/PrincessLog/build

**Comment by SonicMastr** [comment]
I have actually confirmed that it is indeed just too little memory allocated for the normal memory. The game only had 100MB of RAM to work with while Graphics had the other 265 + VRAM. Adjusting it so it had 221MB of RAM allowed it to boot. This wasn't anything on your end, simply an oversight
![PZbwbLn7u9](https://user-images.githubusercontent.com/40341589/181103257-680676c7-1e38-4a7b-a00d-278a929a94db.png)
h

**Comment by SonicMastr** [comment]
Fixed (for this at least) in 2da61d0

It'll be a short while before I actually update the template though

**Comment by L1ghtingBolt** [comment]
Cool, thanks!

**Comment by L1ghtingBolt** [comment]
I compiled the latest commit and still does not work. What changes do the template need?

**Comment by SonicMastr** [comment]
Nothing. A normal build of the template fixes the issue. All I had to do was drag the finished eboot

**Comment by L1ghtingBolt** [comment]
Then why is it not working for me...?
